### PR TITLE
Improve code quality by securing supply chain

### PR DESCRIPTION
**Pull request by MTRNord**
(Arguable this isn't necessary, but I want to learn this for the future.)

## Observed further optimization possibilities
- Playwright Tests probably should have their own Dockerfile to run on so the ubuntu repos can be blocked.
- Pull Requests trigger deploy CI. This should not happen :o

### CODE REVIEW

**Comment by varunsh-coder** [comment]
Hi @MTRNord I observed you tried https://app.stepsecurity.io to address security issues. Please let me know if you have any feedback. I will be happy to help out. Thanks!

**Comment by MTRNord** [comment]
> Hi @MTRNord I observed you tried https://app.stepsecurity.io to address security issues. Please let me know if you have any feedback. I will be happy to help out. Thanks!

Thanks for making this if anything comes up I will write some feedback 👍

**Comment by varunsh-coder** [comment]
> > Hi @MTRNord I observed you tried https://app.stepsecurity.io to address security issues. Please let me know if you have any feedback. I will be happy to help out. Thanks!
> 
> Thanks for making this if anything comes up I will write some feedback 👍

If you run the playwright tests in audit mode, as below, then you will get all the endpoints at once. Then you can add all at once, and change it to `block`

```
- name: Harden Runner
         uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
         with:
           egress-policy: audit
           allowed-endpoints: 
             github.com:22
             github.com:443
             registry.npmjs.org:443
             playwright.azureedge.net:443
             azure.archive.ubuntu.com:443
             azure.archive.ubuntu.com:80
             security.ubuntu.com:80
             packages.microsoft.com:80
             packages.microsoft.com:443
```

**Comment by MTRNord** [comment]
> > > Hi @MTRNord I observed you tried https://app.stepsecurity.io to address security issues. Please let me know if you have any feedback. I will be happy to help out. Thanks!
> > 
> > 
> > Thanks for making this if anything comes up I will write some feedback 👍
> 
> If you run the playwright tests in audit mode, as below, then you will get all the endpoints at once. Then you can add all at once, and change it to `block`
> 
> ```
> - name: Harden Runner
>          uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
>          with:
>            egress-policy: audit
>            allowed-endpoints: 
>              github.com:22
>              github.com:443
>              registry.npmjs.org:443
>              playwright.azureedge.net:443
>              azure.archive.ubuntu.com:443
>              azure.archive.ubuntu.com:80
>              security.ubuntu.com:80
>              packages.microsoft.com:80
>              packages.microsoft.com:443
> ```

Yeah I say that :) Here it was more an issue that the specific pipeline was broken initially due to a bug with npm  :) So it stretched a little more than I wanted it to :)

**Comment by MTRNord** [comment]
(Test failure is not related to the content of the PR, hence it will be fixed in a separate PR)

**Comment by varunsh-coder** [comment]
Hi @MTRNord , I am curious why you did not add these domains to the `allowed-endpoints` list? Is it that you don't think these are needed? They will show up as annotations in every run and I am wondering if there is a better user experience.

**Comment by MTRNord** [comment]
> Hi @MTRNord , I am curious why you did not add these domains to the `allowed-endpoints` list (e.g. fonts.gstatic.com)? Is it that you don't think these are needed? They will show up as annotations in every run and I am wondering if there is a better user experience. https://github.com/MTRNord/matrix-art/actions/runs/1725841456

The end to end UI tests that are running currently don't check for fonts and similar. So it is fine if the font falls back to the browser default. There is not really a good reason to not allow them to be honest :) I just wanted to rewrite that specific job, so I don't have to open the access to the package sources. So I focused on the other things first and want to come back to that one job in another PR :)

**Pull request merged**
